### ISSUE TITLE
Your payment information is formatted improperly. 

### ISSUE THREAD

**Issue by jasonkneen** [hansemannn/titanium-apple-pay#5]
When submitting an order to Stripe based on a currency, total and one summary item, when submitting I get the following:

`Your payment information is formatted improperly. Please make sure you're correctly using the latest version of our iOS library. For more information see https://stripe.com/docs/mobile/ios. (Code: 50)`

There's nothing else logged (i.e. what is being sent to the Stripe server) and this is on simulator using a simulated card.

**Comment by jasonkneen** [comment]
Apparently, this is an issue on simulator -- get's past this on device -- there's a fix that can be done to make it work on sim.

mentioned here https://stackoverflow.com/questions/27241112/issue-with-apple-pay-stripe-integration

**Comment by hansemannn** [comment]
If like you, please do a pull request to add this note to the readme. Thank you!
